import type { Metadata } from "next";
import { IBM_Plex_Sans_KR, JetBrains_Mono } from 'next/font/google';
import "./globals.css";


const plex = IBM_Plex_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-sans',
});

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plex.variable} ${jetbrains.variable}`}
    >
      <body className="m-0 p-0 bg-bg-base">
        {children}
        </body>
    </html>
  );
}
